### ISSUE TITLE
Support hovercasting while in mouselook

### ISSUE THREAD

**Issue by huppopotamus** [MouselookHandler/MouselookHandler#11]
I've been looking everywhere for this functionality and can't seem to find it, so it may just not be possible...

I'm using Clique for spellcasting with hovercast, and a weakaura that adds basically a target circle, and I want to also use this addon to lock the camera to my mouse so the game plays more like a 3rd person shooter. Problem is, the cursor disappears when mouselook mode is on (still have my weakaura), and hovering over units doesn't "select" them as a target for hovercasting.

I basically want to not have to target things via clicking or tabbing, so I can rely exclusively on "aiming" like you would in a 3rd person rpg.

**Comment by meribold** [comment]
This comes up occasionally (e.g. [here](https://www.curseforge.com/wow/addons/mouselookhandler#c132)) and I also thought about it before. I'm quite certain it isn't possible with an interface addon. In theory you could probably create keyboard macros that simulate multiple keypresses a few milliseconds apart, and use those to first disengage mouselook and then run a `[@mouseover]` macro. Perhaps doing so could be considered a ToS violation, though.

**Comment by huppopotamus** [comment]
I briefly attempted this but I'm not overly familiar with wow's interface api, or lua, but I found that hovercasting as a means of dedicated healing (in the 3d world) isn't really practical, at least not for me, and at least not without other addons to make targeting with your hovercast easier
