### ISSUE TITLE
Addon not working, assume it's a shadowlands issue.

### ISSUE THREAD

**Issue by Gromit6909** [MouselookHandler/MouselookHandler#12]
When trying to access the settings menu for the addon I'm faced with a wall of text/error message.
![Untitled](https://user-images.githubusercontent.com/77018752/103679416-b3710680-4f7c-11eb-9866-9e06b4c7d621.jpg)

**Comment by Gromit6909** [comment]
I have used both commands /mh and /mouselookhandler

**Comment by meribold** [comment]
Are you using version 1.3.13?
