### ISSUE TITLE
Mouse look addon options not showing in new patch

### ISSUE THREAD

**Issue by ychnh** [MouselookHandler/MouselookHandler#7]
Addon menus doesn't show in the new patch. Was working yesterday. Stopped working today.

**Comment by meribold** [comment]
Hi @ychnh, could you try [v1.3.13-rc.1](https://github.com/MouselookHandler/MouselookHandler/releases/tag/v1.3.13-rc.1)?

**Comment by Japanties** [comment]
Made an account to say that using v1.3.13-rc.1 fixed this issue for me.

**Comment by meribold** [comment]
Thanks @Japanties!
